FROM python:3.8.10
COPY ./model.py ./trainer.py ./run.py ./scripts/container_shutdown.sh ./dataset.py ./
RUN pip install torch==2.0.0+cpu torchvision==0.15.1+cpu --index-url https://download.pytorch.org/whl/cpu

ENV resume="false"

RUN chmod +x ./container_shutdown.sh

ENTRYPOINT ./container_shutdown.sh ${resume}